name: Types

on:
  push:
    branches:
      - master
    tags:
      - "*"

  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: build-types
  cancel-in-progress: true

jobs:
  deploy-types:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm i
          npm install -g tsc-alias

      - name: Build Declarations Only
        run: |
          npx tsc --emitDeclarationOnly --declaration --removeComments --outDir dist --project tsconfig.json
          tsc-alias

      - name: Prepare Clean package.json
        run: |
          jq 'del(
            .scripts,
            .dependencies,
            .devDependencies,
            .peerDependencies,
            .optionalDependencies,
            .bundledDependencies
          )' package.json > dist/package.json
          rm package.json
          mv dist/package.json package.json

      - name: Push to `types` Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout --orphan types
          git reset -q HEAD --

          git add -f -A dist LICENSE package.json
          git commit -m "Deploy type definitions only"
          git push origin types --force

      - name: Push to `types-only` Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout --orphan types-only
          git reset -q HEAD --

          cat << EOF > dist/index.d.ts
          import { ValtheraTypes } from "./types/export";
          import { RelationTypes } from "./types/relation";
          import { ValtheraCompatible } from "./types/valthera";
          export type { RelationTypes, ValtheraCompatible, ValtheraTypes };
          export type Id = import("./types/Id").Id;
          EOF

          echo "export {}" > dist/index.js

          git add -f -A dist/types dist/index.d.ts dist/index.js LICENSE package.json
          git commit -m "Deploy type definitions only"
          git push origin types-only --force
